### ISSUE TITLE
hooks support

### ISSUE THREAD

**Issue by shirbr510** [rjerue/react-decision-tree-flow#1]
hey :)
just stumbled upon your project when I was looking to see if someone already did what I'm trying to do

I think that now, after hooks has been released, the hooks syntax is the "de-facto" way to define declarative react logic

do you consider adding support for hooks syntax?

**Comment by rjerue** [comment]
Hey, have you seen https://github.com/rjerue/react-decision-tree-flow/blob/master/README.md#hooks ?

Let me know if you have any other questions/suggestions! 😉

**Comment by shirbr510** [comment]
Nope, I haven't seen it :)

My only question would be about the tiny note that the hook must remain inside the wizard's context

Shouldn't the usage of hooks replace the need of a wizard component?

**Comment by rjerue** [comment]
> Nope, I haven't seen it :)
> 
> My only question would be about the tiny note that the hook must remain inside the wizard's context
> 
> Shouldn't the usage of hooks replace the need of a wizard component?

The component is leveraging react context, it needs to be inside of a wizards context as that is where the root is being defined. This way, you can have multiple wizards at sibling level.
