### ISSUE TITLE
Does not render

### ISSUE THREAD

**Issue by cbfrance** [rjerue/react-decision-tree-flow#2]
When I installed it with the demo code, it fails to render and just displays the text from inside the JSX. The demo from the readme has the same behavior.

**Comment by rjerue** [comment]
> When I installed it with the demo code, it fails to render and just displays the text from inside the JSX. The demo from the readme has the same behavior.

Hello!

I'd be happy to help troubleshoot this. It seems to be rendering fine however in an environment that I just set up. https://codesandbox.io/s/elated-sutherland-p1ps5?fontsize=14&hidenavigation=1&theme=dark

Could you provide me with a sample repo/codesandbox, so that I can replicate the issue?

**Comment by cbfrance** [comment]
Hi, thanks, interesting, that example doesn't seem to work for me in latest chrome or Firefox. I only see plain text `I am step 1` and `Go to Step 2`. 

(It's possible perhaps I am misunderstanding the purpose of the library, but it didn't match my expectations based on the Readme.) 

![Screen Shot 2020-02-02 at 2 14 58 PM](https://user-images.githubusercontent.com/7366/73616307-a3abae00-45c6-11ea-9c6c-df8299ee4fc6.png)

Screenshot of the plain text rendering which I am seeing.

**Comment by rjerue** [comment]
It's working correctly. Click on `GO TO _` and the state of the wizard will change. What are you expecting to render?

The code for the example and this story move things when the div is clicked. https://github.com/rjerue/react-decision-tree-flow/blob/master/stories/ComplicatedTree.js. What expectations did you have?

**Comment by cbfrance** [comment]
Oh, ha! I understand my confusion now; I thought it rendered a flow chart like the image in the readme. (Apparently I didn’t parse or understand the reference to the “wizard.”) Makes sense now. This seems useful! Thanks for helping.
