### ISSUE TITLE
Custom Props for Step

### ISSUE THREAD

**Issue by maxwolfs** [rjerue/react-decision-tree-flow#3]
First of all thanks for sharing this nice lib!

For my purpose I have some questions:
 
How is it possible to have more props for each step? 
For example a title, text and media such as an image or even a markdown document?

Merci!

**Comment by rjerue** [comment]
Hello,

I'm currently in the midst of a rewrite for this, but in the current case, and in the future, all you need to do is pass down a child into step.

Something similar to below:

```jsx
const StepWithImg = () => {
  return (
    <Step name="myStep">
      <img src="https://avatars2.githubusercontent.com/u/4666313?s=80&v=4"/>
    </Step>
  );
}
```

I encourage you to try it out in something like https://codesandbox.io/

**Comment by rjerue** [comment]
Over a week with no response. Closing, please re-open if you have more questions.
