### ISSUE TITLE
Back support

### ISSUE THREAD

**Issue by hwhh** [rjerue/react-decision-tree-flow#5]
### Feature request

It would be great if there was an easy way to support a back button, without having to add all the previous steps the destinations of the current step

**Comment by rjerue** [comment]
Hey,

I agree, this would be a useful add. Probably wouldn't be too hard for me to include. Will see what I can do.

**Comment by rjerue** [comment]
Hey @hwhh. I've made a pull request with support for a back button. https://github.com/rjerue/react-decision-tree-flow/pull/6

Basically it's just another function returned by the controls render prop or hook called `back` that will allow for folks to go to the previous state in the wizard. If you passed data via the wizard, it'll even restore that. There's an override for the data restoration through passing new data in through the back function. Would love for you to leave feedback there.
