### ISSUE TITLE
Storing responses

### ISSUE THREAD

**Issue by lbhtran** [rjerue/react-decision-tree-flow#7]
Hi, thank you for a great library. I'm using this to build a questionnaire app. Is there a way to store the responses to all of the steps?

**Comment by rjerue** [comment]
> Hi, thank you for a great library. I'm using this to build a questionnaire app. Is there a way to store the responses to all of the steps?

Hi, sorry for the delay in getting back. I'm not sure it is in scope of this library. If you have a repo, I'd be happy to give any tips!

**Comment by rjerue** [comment]
Closed due to inactivity.
